### ISSUE TITLE
Create module for translating NL to API

### ISSUE THREAD

**Issue by IKostric** [iai-group/pkg-api#57]
- [x] #61
- [x] [NLtoPKG] Update pipeline to match the paper
- [x] [NLtoPKG] Implement simple three-step annotator
- [x] [NLtoPKG] Create folder with prompts #72 
- [x] [NLtoPKG] Add prompts using examples defined in #40
- [x] [NLtoPKG] Create method for loading the prompts based on path
- [x] [NLtoPKG] Create method to call llama
- [x] #81
- [ ] [NLtoPKG] (Optional) Create method for calling other LLM models
- [ ] [NLtoPKG] (Optional) Implement JointBERT model
- [ ] [NLtoPKG] Try other LLMs #68 
- [x] [NLtoPKG] Create a microbenchmark for comparing models.
- [ ] [NLtoPKG] Compare LLama, Mistral and OpenAI models using the mcirobenchmark.
- [x] [NLtoPKG] Implement off-the-shelf entity linker
